#!/usr/bin/env bash

## Check if brew is installed and install it if not
which -s brew
if [[ $? != 0 ]] ; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
    brew update
fi

## Install ansible
brew install ansible

## pull ansible
ansible-pull -C main -U https://github.com/CxGarcia/ansible.git
