- name: Install packages
  become: false
  tags:
    - core
    - mac
  homebrew:
    state: present
    name:
      [
        "wget",
        "gmp",
        "nmap",
        "grep",
        "node",
        "git",
        "git-lfs",
        "github/gh/gh",
        "zsh",
        "fnm",
        "stow",
      ]

- name: Install casks
  become: false
  tags:
    - core
    - mac
  homebrew:
    install_options: cask
    state: present
    upgrade_all: yes
    name:
      [
        "iterm2",
        "notion",
        "spotify",
        "vlc",
        "visual-studio-code",
        "karabiner-elements",
        "hammerspoon",
      ]
